### ISSUE TITLE
Bibliography error 

### ISSUE THREAD

**Issue by kaya4me2** [NASA-Planetary-Science/sbpy-tutorial#26]
spy version: 0.2.3.dev223+g9eb0523

attempt in Jupyter notebook cell:

print(bib.to_text())

results in following error (perhaps a format error in the bibliography entries?)

/anaconda3/envs/sbpy/lib/python3.7/site-packages/ads/base.py:135: RuntimeWarning: No token found
  warnings.warn("No token found", RuntimeWarning)

---------------------------------------------------------------------------
APIResponseError                          Traceback (most recent call last)
/var/folders/bg/mn56s0j97kb5t5d_2fv9d8m40000gn/T/ipykernel_90232/1509855751.py in <module>
----> 1 print(bib.to_text())

/anaconda3/envs/sbpy/lib/python3.7/site-packages/sbpy/bib/core.py in to_text(filter)
    256                                     bibcode=citation,
    257                                     fl=['first_author', 'author', 'volume',
--> 258                                         'pub', 'issue', 'page', 'year']
    259                                 ))[0]
    260                         except (IndexError, Warning, RuntimeWarning) as e:

/anaconda3/envs/sbpy/lib/python3.7/site-packages/ads/search.py in __next__(self)
    499         # explicitly
    500         if self.response is None:
--> 501             self.execute()
    502 
    503         try:

/anaconda3/envs/sbpy/lib/python3.7/site-packages/ads/search.py in execute(self)
    531         """
    532         self.response = SolrResponse.load_http_response(
--> 533             self.session.get(self.HTTP_ENDPOINT, params=self.query)
    534         )
    535 

/anaconda3/envs/sbpy/lib/python3.7/site-packages/ads/base.py in load_http_response(cls, http_response)
     92         """
     93         if not http_response.ok:
---> 94             raise APIResponseError(http_response.text)
     95         c = cls(http_response)
     96         c.response = http_response

APIResponseError: '{\n  "error": "Unauthorized"\n}\n'

**Comment by jianyangli** [comment]
Hi @kaya4me2 , it was pointed out that a ADS token is needed in order for the `ads` module to work, which what `sbpy.bib` is built upon.  See https://sbpy.readthedocs.io/en/latest/sbpy/bib.html for how to set up the token.  Let me know if it works for you and we can close this issue.  Thanks.

**Comment by kaya4me2** [comment]
Hi jianyangli

You suggestion re: getting the ADS token setup, storing the key in ~/.ads/dev_key, and then pip install fixes one problem with the bib call ...

%% code versions
numpy == 1.22.3
sbpy == 0.2.3.dev223+g9eb0523
astroquery == 0.4.6.dev7540
ads == 0.12.3

**However the original problem remains running code from Jupiter notebook** 

from sbpy.data import Orbit
from astropy.time import Time
epoch = Time('2018-05-14', scale='tdb')  
eph = Orbit.from_horizons('Ceres', epochs=epoch)  

throws error:

SSLError                                  Traceback (most recent call last)
File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/urllib3/connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    702 # Make the request on the httplib connection object.
--> 703 httplib_response = self._make_request(
    704     conn,
    705     method,
    706     url,
    707     timeout=timeout_obj,
    708     body=body,
    709     headers=headers,
    710     chunked=chunked,
    711 )
    713 # If we're going to release the connection in ``finally:``, then
    714 # the response doesn't need to know about the connection. Otherwise
    715 # it will also try to release it and we'll have a double-release
    716 # mess.

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/urllib3/connectionpool.py:386, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    385 try:
--> 386     self._validate_conn(conn)
    387 except (SocketTimeout, BaseSSLError) as e:
    388     # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/urllib3/connectionpool.py:1040, in HTTPSConnectionPool._validate_conn(self, conn)
   1039 if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1040     conn.connect()
   1042 if not conn.is_verified:

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/urllib3/connection.py:414, in HTTPSConnection.connect(self)
    412     context.load_default_certs()
--> 414 self.sock = ssl_wrap_socket(
    415     sock=conn,
    416     keyfile=self.key_file,
    417     certfile=self.cert_file,
    418     key_password=self.key_password,
    419     ca_certs=self.ca_certs,
    420     ca_cert_dir=self.ca_cert_dir,
    421     ca_cert_data=self.ca_cert_data,
    422     server_hostname=server_hostname,
    423     ssl_context=context,
    424     tls_in_tls=tls_in_tls,
    425 )
    427 # If we're using all defaults and the connection
    428 # is TLSv1 or TLSv1.1 we throw a DeprecationWarning
    429 # for the host.

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/urllib3/util/ssl_.py:449, in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)
    448 if send_sni:
--> 449     ssl_sock = _ssl_wrap_socket_impl(
    450         sock, context, tls_in_tls, server_hostname=server_hostname
    451     )
    452 else:

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/urllib3/util/ssl_.py:493, in _ssl_wrap_socket_impl(sock, ssl_context, tls_in_tls, server_hostname)
    492 if server_hostname:
--> 493     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
    494 else:

File /opt/anaconda3/envs/sb3/lib/python3.8/ssl.py:500, in SSLContext.wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    494 def wrap_socket(self, sock, server_side=False,
    495                 do_handshake_on_connect=True,
    496                 suppress_ragged_eofs=True,
    497                 server_hostname=None, session=None):
    498     # SSLSocket class handles server_hostname encoding before it calls
    499     # ctx._wrap_socket()
--> 500     return self.sslsocket_class._create(
    501         sock=sock,
    502         server_side=server_side,
    503         do_handshake_on_connect=do_handshake_on_connect,
    504         suppress_ragged_eofs=suppress_ragged_eofs,
    505         server_hostname=server_hostname,
    506         context=self,
    507         session=session
    508     )

File /opt/anaconda3/envs/sb3/lib/python3.8/ssl.py:1040, in SSLSocket._create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1039             raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1040         self.do_handshake()
   1041 except (OSError, ValueError):

File /opt/anaconda3/envs/sb3/lib/python3.8/ssl.py:1309, in SSLSocket.do_handshake(self, block)
   1308         self.settimeout(None)
-> 1309     self._sslobj.do_handshake()
   1310 finally:

SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1131)

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/requests/adapters.py:440, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    439 if not chunked:
--> 440     resp = conn.urlopen(
    441         method=request.method,
    442         url=url,
    443         body=request.body,
    444         headers=request.headers,
    445         redirect=False,
    446         assert_same_host=False,
    447         preload_content=False,
    448         decode_content=False,
    449         retries=self.max_retries,
    450         timeout=timeout
    451     )
    453 # Send the request.
    454 else:

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/urllib3/connectionpool.py:785, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    783     e = ProtocolError("Connection aborted.", e)
--> 785 retries = retries.increment(
    786     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    787 )
    788 retries.sleep()

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/urllib3/util/retry.py:592, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    591 if new_retry.is_exhausted():
--> 592     raise MaxRetryError(_pool, url, error or ResponseError(cause))
    594 log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)

MaxRetryError: HTTPSConnectionPool(host='ssd.jpl.nasa.gov', port=443): Max retries exceeded with url: /api/horizons.api?format=text&EPHEM_TYPE=ELEMENTS&MAKE_EPHEM=YES&OUT_UNITS=AU-D&COMMAND=%22Ceres%3B%22&CENTER=%27500%4010%27&CSV_FORMAT=YES&ELEM_LABELS=YES&OBJ_DATA=YES&REF_SYSTEM=ICRF&REF_PLANE=ECLIPTIC&TP_TYPE=ABSOLUTE&TLIST=2458252.5 (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
Input In [5], in <cell line: 5>()
      2 from astropy.time import Time
      4 epoch = Time('2018-05-14', scale='tdb')  
----> 5 eph = Orbit.from_horizons('Ceres', epochs=epoch)

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/sbpy/bib/core.py:171, in cite.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    168 @wraps(f)
    169 def wrapper(*args, **kwargs):
    170     # only cite after successful call
--> 171     result = f(*args, **kwargs)
    172     register(f, citations)
    173     return result

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/sbpy/bib/core.py:171, in cite.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    168 @wraps(f)
    169 def wrapper(*args, **kwargs):
    170     # only cite after successful call
--> 171     result = f(*args, **kwargs)
    172     register(f, citations)
    173     return result

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/sbpy/data/orbit.py:161, in Orbit.from_horizons(cls, targetids, id_type, epochs, center, **kwargs)
    158 obj = Horizons(id=targetid, id_type=id_type,
    159                location=center, epochs=epochs)
    160 try:
--> 161     elem = obj.elements(**kwargs)
    162 except ValueError as e:
    163     raise QueryError(
    164         ('Error raised by astroquery.jplhorizons: {:s}\n'
    165          'The following query was attempted: {:s}').format(
    166              str(e), obj.uri))

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/astroquery/utils/class_or_instance.py:25, in class_or_instance.__get__.<locals>.f(*args, **kwds)
     23 def f(*args, **kwds):
     24     if obj is not None:
---> 25         return self.fn(obj, *args, **kwds)
     26     else:
     27         return self.fn(cls, *args, **kwds)

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/astroquery/utils/process_asyncs.py:26, in async_to_sync.<locals>.create_method.<locals>.newmethod(self, *args, **kwargs)
     22 @class_or_instance
     23 def newmethod(self, *args, **kwargs):
     24     verbose = kwargs.pop('verbose', False)
---> 26     response = getattr(self, async_method_name)(*args, **kwargs)
     27     if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28         return response

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/astroquery/jplhorizons/core.py:803, in HorizonsClass.elements_async(self, get_query_payload, refsystem, refplane, tp_type, closest_apparition, no_fragments, get_raw_response, cache)
    800     self.return_raw = True
    802 # query and parse
--> 803 response = self._request('GET', URL, params=request_payload,
    804                          timeout=self.TIMEOUT, cache=cache)
    805 self.uri = response.url
    807 # check length of uri

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/astroquery/query.py:317, in BaseQuery._request(self, method, url, params, data, headers, files, save, savedir, timeout, cache, stream, auth, continuation, verify, allow_redirects, json, return_response_on_save)
    315     response = query.from_cache(self.cache_location)
    316     if not response:
--> 317         response = query.request(self._session,
    318                                  self.cache_location,
    319                                  stream=stream,
    320                                  auth=auth,
    321                                  allow_redirects=allow_redirects,
    322                                  verify=verify,
    323                                  json=json)
    324         to_cache(response, query.request_file(self.cache_location))
    325 self._last_query = query

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/astroquery/query.py:71, in AstroQuery.request(self, session, cache_location, stream, auth, verify, allow_redirects, json)
     68 def request(self, session, cache_location=None, stream=False,
     69             auth=None, verify=True, allow_redirects=True,
     70             json=None):
---> 71     return session.request(self.method, self.url, params=self.params,
     72                            data=self.data, headers=self.headers,
     73                            files=self.files, timeout=self.timeout,
     74                            stream=stream, auth=auth, verify=verify,
     75                            allow_redirects=allow_redirects,
     76                            json=json)

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/requests/sessions.py:529, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    524 send_kwargs = {
    525     'timeout': timeout,
    526     'allow_redirects': allow_redirects,
    527 }
    528 send_kwargs.update(settings)
--> 529 resp = self.send(prep, **send_kwargs)
    531 return resp

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/requests/sessions.py:645, in Session.send(self, request, **kwargs)
    642 start = preferred_clock()
    644 # Send the request
--> 645 r = adapter.send(request, **kwargs)
    647 # Total elapsed time of the request (approximately)
    648 elapsed = preferred_clock() - start

File /opt/anaconda3/envs/sb3/lib/python3.8/site-packages/requests/adapters.py:517, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    513         raise ProxyError(e, request=request)
    515     if isinstance(e.reason, _SSLError):
    516         # This branch is for urllib3 v1.22 and later.
--> 517         raise SSLError(e, request=request)
    519     raise ConnectionError(e, request=request)
    521 except ClosedPoolError as e:

SSLError: HTTPSConnectionPool(host='ssd.jpl.nasa.gov', port=443): Max retries exceeded with url: /api/horizons.api?format=text&EPHEM_TYPE=ELEMENTS&MAKE_EPHEM=YES&OUT_UNITS=AU-D&COMMAND=%22Ceres%3B%22&CENTER=%27500%4010%27&CSV_FORMAT=YES&ELEM_LABELS=YES&OBJ_DATA=YES&REF_SYSTEM=ICRF&REF_PLANE=ECLIPTIC&TP_TYPE=ABSOLUTE&TLIST=2458252.5 (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1131)')))

In [22]:

**Comment by jianyangli** [comment]
@kaya4me2 Looks like this is the issue that you raised originally in https://github.com/NASA-Planetary-Science/sbpy/issues/323#issue-1167705530.

Since the `sbpy.bib` problem you reported here is solved, I'm going to close this issue.  Let's track the `Orbit.from_horizons` problem you had through the original issue.  I'll follow up with you there.  Thanks.
